yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # 1 Главная страница (ВСЕМ)
    path('', views.index, name='index'),
    # 2 Отображение всех записей группы (ВСЕМ)
    path('group/<str:slug>/', views.group_posts, name='group_list'),
    # 3 Профайл пользователя (ВСЕМ)
    path('profile/<str:username>/', views.profile, name='profile'),
    # 4 Просмотр записи (ВСЕМ)
    path('posts/<int:post_id>/', views.post_view, name='post_detail'),
    # 5 Редактирование записи (АВТОРУ)
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # 6 Создание нового поста (АВТОРИЗОВАННОМУ)
    path('create/', views.post_create, name='post_create'),
    # 7 Комментирование поста
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    # 8
    path(
        'follow/',
        views.follow_index,
        name='follow_index'),
    # 9
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # 10
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/',
         LogoutView.as_view(template_name='registration/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(template_name='registration/login.html'),
         name='login'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='post')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

# if DEBUG=TRUE:
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/include/author_card.html
<div class="col-md-3 mb-3 mt-1">
  <div class="card">
    <div class="card-body">
      <div class="h2">
        {{ author.get_full_name }}
      </div>
      <div class="h3 text-muted">
        @{{ author.username }}
      </div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="h6 text-muted">
          Подписчиков: {{ author.following.count }} <br>
          Подписан: {{ author.follower.count }}
        </div>
      </li>
      <li class="list-group-item">
        <div class="h6 text-muted">
          Записей: {{ author.posts.count }}
        </div>
      </li>
      {% if request.user != author %}
          {% if following %}
              <a class="btn btn-lg btn-light"
                 href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                  Отписаться
              </a>
          {% else %}
              <a class="btn btn-lg btn-primary"
                 href="{% url 'posts:profile_follow' author.username %}" role="button">
                  Подписаться
              </a>
          {% endif %}
      {% endif %}
    </ul>
  </div>
</div>

yatube/templates/include/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/include/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
  <p class="m-0 text-dark text-center ">
    Социальная сеть <span style="color:red">Ya</span>tube ©  {{ year }}, все права защищены.
  </p>
</footer>

yatube/templates/include/group_card.html
{#добавила для идентичности решения страниц с постами#}
<div class="col-md-3 mb-3 mt-1">
  <div class="card">
    <div class="card-body">
      <div class="h2">
        {{ group.title }}
      </div>
      <div class="h3 text-muted">
        @{{ group.title }}
      </div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="h6 text-muted">
{#            следующая строчка для теста#}
{#          <p>{{ group.description }}</p>#}
{#            а так мне больше нравится:#}
{#            одинаковый отступ снизу с group.post.count и author.posts.count #}
          Описание группы: {{ group.description }}
        </div>
      </li>
      <li class="list-group-item">
        <div class="h6 text-muted">
          Записей: {{ group.posts.count }}
        </div>
      </li>
    </ul>
  </div>
</div>

yatube/templates/include/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="/"><span style="color:#e70f0f">Ya</span>tube The Last Social Media You'll Ever Need</a>

  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
      Пользователь:
      <a class="p-2 text-dark" href="{% url 'posts:profile' user.username %}">{{ user.username }}</a>
      <a class="p-2 text-dark" href="{% url 'posts:post_create' %}">Новая запись</a>
      <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'users:signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav>

yatube/templates/include/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/include/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Мои подписки
        </a>
      </li>
    </ul>
  </div>
{% endif %}

{#думала switcher засунуть в аналогичную конструкцию как author_card и group_card#}
{#но не понравилось пока#}
{#{% if user.is_authenticated %}#}
{#    <div class="col-md-3 mb-3 mt-1">#}
{#        <div class="card">#}
{#            <ul class="list-group list-group-flush">#}
{#                <li class="list-group-item">#}
{#                    <div class="h5">#}
{#                        <a class="nav-link {% if index %}active{% endif %}"#}
{#                           href="{% url 'posts:index' %}">Все авторы#}
{#                        </a>#}
{#                    </div>#}
{#                </li>#}
{#                <li class="list-group-item">#}
{#                    <div class="h5 text-muted">#}
{#                        <a class="nav-link {% if follow %}active{% endif %}"#}
{#                           href="{% url 'posts:follow_index' %}">Мои подписки#}
{#                        </a>#}
{#                    </div>#}
{#                </li>#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{#{% endif %}#}