yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # 1 Главная страница (ВСЕМ)
    path('', views.index, name='index'),
    # 2 Отображение всех записей группы (ВСЕМ)
    path('group/<str:slug>/', views.group_posts, name='group_list'),
    # 3 Профайл пользователя (ВСЕМ)
    path('profile/<str:username>/', views.profile, name='profile'),
    # 4 Просмотр записи (ВСЕМ)
    path('posts/<int:post_id>/', views.post_view, name='post_detail'),
    # 5 Редактирование записи (АВТОРУ)
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # 6 Создание нового поста (АВТОРИЗОВАННОМУ)
    path('create/', views.post_create, name='post_create'),
    # 7 Комментирование поста
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    # 8
    path(
        'follow/',
        views.follow_index,
        name='follow_index'),
    # 9
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # 10
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='post')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

# if DEBUG=TRUE:
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название сообщества',
                             max_length=200,
                             help_text='Дайте название сообществу'
                             )
    slug = models.SlugField(unique=True)
    # AE: Свойство `description` модели `Group` должно быть `TextField` ))
    description = models.TextField('Описание сообщества')

    class Meta:
        pass

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'post text',
        help_text='enter post text'
    )
    pub_date = models.DateTimeField(
        'date published',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='author'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='group',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text = 'Выберите картинку'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(
        'date published',
        auto_now_add=True
    )


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower'
                             )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following'
                               )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self) -> str:
        return f'{self.user.username}-->{self.author.username}'

yatube/posts/forms.py
from django import forms
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['group', 'text', 'image']
        help_texts = {
            'text': 'Введите текст',
            'group': 'Выберите группу',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        text = forms.CharField(widget=forms.Textarea)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


@cache_page(20)
def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all().order_by('-pub_date')
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = request.user.is_authenticated and Follow.objects.filter(
        author__username=username, user=request.user).exists()
    posts_of_user = author.posts.all()
    paginator = Paginator(posts_of_user, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_view(request, post_id):
    post = Post.objects.get(id=post_id)
    form = CommentForm(request.POST or None)
    context = {
        'author': post.author,
        'post': post,
        'form': form
    }
    return render(request, 'posts/post.html', context)


def post_detail(request, username, post_id):
    author = User.objects.get(username=username)
    post = author.posts.get(id=post_id)
    form = CommentForm()
    context = {
        'author': author,
        'post': post,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,)
    if request.method == 'POST':
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            form.save()
            return redirect(f'/profile/{request.user}/')
    context = {
        'form': form
    }
    return render(request, 'posts/new_post.html', context)


@login_required
def post_edit(request, post_id: int):
    post = get_object_or_404(Post, pk=post_id)

    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id=post_id)
    context = {
        'is_edit': True,
        'form': form,
        'post_id': post_id,
        'post': post,
    }
    return render(request, 'posts/new_post.html', context)




@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    deleting_follow = get_object_or_404(Follow, user=user, author=author)
    deleting_follow.delete()
    return redirect('posts:profile', username=author.username)

yatube/posts/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{ title }}{% endblock %}
{#{% block header %}Последние обновления на сайте{% endblock %}#}

{% block content %}
    <main role="main" class="container">
        <div class="mb-5">
            <h1>Последние обновления на сайте</h1>
        </div>
        <div>
            <h1>Авторы, на которых вы подписаны:</h1>
        </div>

        <div class="row">
            {% include 'include/switcher.html' %}
            <div class="col-md-12">
                {% if request.user.follower.count == 0 %}
                    <h4>Вы ещё ни на кого не подписаны...</h4>
                {% else %}
                    {% for post in page_obj %}
                        <div class="card mb-3 mt-1 shadow-sm">
                            <div class="card-body">
                                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                                     <img class="card-img my-2" src="{{ im.url }}">
                                {% endthumbnail %}
                                <ul>
                                     <li>
                                        Автор: {{ post.author.get_full_name }} /
                                         <a href="{% url 'posts:profile' post.author.username %}">
                                            @{{ post.author.username }}</a>
                                     </li>
                                    <li>
                                        <a href="{% url 'posts:profile' post.author.username %}">
                                             Все посты пользователя</a>
                                    </li>
                                    {% if post.group %}
                                        <li>Группа:
                                            <a href="{% url 'posts:group_list' post.group.slug %}">
                                                {{ post.group.title }}
                                            </a>
                                        </li>
                                    {% endif %}
                                    <p>{{ post.text|truncatewords:62 }}</p>
                                    <a class="btn btn-lg btn-primary"
                                       href="{% url 'posts:post_detail' post.pk %}" role="button">
                                        Подробнее
                                    </a>
                                </ul>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">{{ post.pub_date }}</small>
                                    {% if request.user == post.author %}
                                        <div class="btn-group ">
                                            <a class="btn btn-sm text-muted"
                                               href="/{{ post.author.username }}/{{ post.id }}/edit"
                                               role="button">
                                                Редактировать
                                            </a>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% include "include/paginator.html" %}
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}

yatube/posts/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}
    <main role="main" class="container">
        <div class="mb-5">
            <h1>Все посты группы {{ group }}</h1>
        </div>

        <div class="row">
            {% include "include/group_card.html" %}
            <div class="col-md-9">
                {% for post in page_obj %}
                    <div class="card mb-3 mt-1 shadow-sm">
                        <div class="card-body">
                            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                                <img class="card-img my-2" src="{{ im.url }}">
                            {% endthumbnail %}
                            <ul>
                                <li>
                                    Автор: {{ post.author.get_full_name }}
                                    <a href="{% url 'posts:profile' post.author.username %}">
                                        @{{ post.author.username }}</a>
                                </li>
                                <li>
                                    <a href="{% url 'posts:profile' post.author.username %}">
                                        Все посты пользователя</a>
                                </li>
                                <p>{{ post.text|truncatechars:63 }}</p>
                                <a class="btn btn-lg btn-primary"
                                   href="{% url 'posts:post_detail' post.pk %}" role="button">
                                    Подробнее
                                </a>
                            </ul>
                            <small class="text-muted">{{ post.pub_date }} </small>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
  {% include "include/paginator.html" %}
{% endblock %}

yatube/posts/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{ title }}{% endblock %}
{#{% block header %}Последние обновления на сайте{% endblock %}#}

{% block content %}
    <main role="main" class="container">
        <div class="mb-5">
            <h1>Последние обновления на сайте</h1>
        </div>
        <div>
            <h1>Все авторы на сайте:</h1>
        </div>

        <div class="row">
            {% include 'include/switcher.html' %}
            <div class="col-md-12">
                {% for post in page_obj %}
                    <div class="card mb-3 mt-1 shadow-sm">
                        <div class="card-body">
                            {% thumbnail post.image "960x320" crop="center" upscale=True as im %}
                                <img class="card-img my-2" src="{{ im.url }}">
                            {% endthumbnail %}
                            <ul>
                                <li>
                                    Автор: {{ post.author.get_full_name }} /
                                    <a href="{% url 'posts:profile' post.author.username %}">
                                        @{{ post.author.username }}</a>
                                </li>
                                <li>
                                    <a href="{% url 'posts:profile' post.author.username %}">
                                        Все посты пользователя</a>
                                </li>
                                <li>
                                    Группа: <!--{{ post.group.title }}-->
                                    {% if post.group %}
                                        <a href="{% url 'posts:group_list' post.group.slug %}">
                                            {{ post.group.title }}
                                        </a>
                                    {% endif %}
                                </li>
                                <p>{{ post.text|truncatechars:62 }}</p>
                                <a class="btn btn-lg btn-primary"
                                   href="{% url 'posts:post_detail' post.pk %}" role="button">
                                    Подробнее
                                </a>
                            </ul>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{ post.pub_date }}</small>
                                {% if request.user == post.author %}
                                  <div class="btn-group ">
                                    <a class="btn btn-sm text-muted"
{#                                       href="/{{ post.author.username }}/{{ post.id }}/edit"#}
                                       href="/posts/{{ post.id }}/edit"
                                       role="button">
                                        Редактировать
                                    </a>
                                  </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% include "include/paginator.html" %}
                {% if not forloop.last %}<hr>{% endif %}
            </div>
            <br>
        </div>
    </main>
{% endblock %}

yatube/posts/templates/posts/new_post.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    {% if is_edit %} Редактировать запись
                    {% else %} Добавить запись
                    {% endif %}
                </div>
                <div class="card-body">
                    {% load user_filters %}
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post" enctype="multipart/form-data" {% if action_url %} action="{% url action_url %}" {% endif %}>
                        {% csrf_token %}
                        {% load user_filters %}
                        <div class="card-body">
                            {% for field in form %}
                                <div class="form-group row my-3">
                                    <label for="{{ field.id_for_label }}">
                                        {{ field.label }}
                                        {% if field.field.required %}
                                            <span class="required text-danger">*</span>
                                        {% endif %}
                                    </label>
                                    {{ field|addclass:'form-control' }}
                                    {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                            {{ field.help_text|safe }}
                                        </small>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">
                                {% if is_edit %} Сохранить
                                {% else %} Добавить
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

yatube/posts/templates/posts/post.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}

{% block content %}
  <main role="main" class="container">
    <div class="row">
    {% include "include/author_card.html" %}

      <div class="col-md-9">
        <div class="card mb-3 mt-1 shadow-sm">
          <div class="card-body">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <ul>
              <li>
                  Автор: {{ post.author.get_full_name }} /
                  <a href="{% url 'posts:profile' post.author.username %}">
                      @{{ post.author.username }}</a>
              </li>
              <li>
                <a href="{% url 'posts:profile' post.author.username %}">
                    Все посты пользователя
                </a>
              </li>
              <li>
                  Группа: <!--{{ post.group.title }}-->
                  {% if post.group %}
                      <a href="{% url 'posts:group_list' post.group.slug %}">
                          {{ post.group.title }}
                      </a>
                  {% endif %}
              </li>
              {{ post.text|linebreaksbr }}
            </ul>
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{ post.pub_date }}</small>
                {% if request.user == author %}
                    <div class="btn-group">
                        <a class="btn btn-sm text-muted"
                           href="/posts/{{ post.pk }}/edit/" role="button">
                            Редактировать пост
                        </a>
                    </div>
                {% endif %}
            </div>
            {% include 'include/comments.html' with form=form comments=post.comments.all %}
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/posts/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %} Пост {{ post.text|truncatechars:30 }} {% endblock %}
{% block content %}
  <div class="container py-5">
    <h1 class="title">{{ title }}</h1>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
              {% if post.group %}
                <li class="list-group-item">
                  Группа: {{ post.group }}
                  <a href="{% url "posts:group_list" post.group.slug %}"
                    class="btn btn-outline-primary">Все записи группы</a>
                </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
                  {{ post.author.username }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url "posts:profile" post.author.username %}"
                class="btn btn-outline-primary">все посты пользователя</a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
        </article>
      </div>
  </div>
{% endblock %}

yatube/posts/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}
    <main role="main" class="container">
        <div class="mb-5">
            <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        </div>

        <div class="row">
            {% include "include/author_card.html" %}
            <div class="col-md-9">
                {% for post in page_obj %}
                    <div class="card mb-3 mt-1 shadow-sm">
                        <div class="card-body">
                            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                                <img class="card-img my-2" src="{{ im.url }}">
                            {% endthumbnail %}
                            <ul>
                                <li>
                                    Автор: {{ post.author.get_full_name }}
                                    <a href="{% url 'posts:profile' post.author.username %}">
                                        @{{ post.author.username }}</a>
                                </li>
                                <li>
                                    Группа: <!--{{ post.group.title }}-->
                                    {% if post.group %}
                                        <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
                                    {% endif %}
                                </li>
                                <p>{{ post.text|truncatechars:63 }}</p>
                                <a class="btn btn-lg btn-primary"
                                   href="{% url 'posts:post_detail' post.pk %}" role="button">
                                    Подробнее
                                </a>
                            </ul>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{ post.pub_date }}</small>
                                {% if request.user == author %}
                                  <div class="btn-group ">
                                    <a class="btn btn-sm text-muted"
                                       href="/posts/{{ post.id }}/edit"
                                       role="button">
                                        Редактировать
                                    </a>
                                  </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% include "include/paginator.html" %}
            </div>
        </div>
    </main>
{% endblock %}